<?php

$rrdaRankingPages = [
    'best-hotels-in-nairobi' => [
        'title' => 'Best Hotels in Nairobi by Online Reputation',
        'short_title' => 'Hotels in Nairobi',
        'description' => 'A ranked Nairobi hotel data pool based on visible online reputation, review footprint, brand visibility and buyer usefulness.',
        'category' => 'Hospitality',
        'location' => 'Nairobi',
        'image' => 'img/services/field-concierge.png',
        'chart_color' => '#00b8d9',
        'cta' => 'Request hotel directory',
        'rows' => [
            ['name' => 'Villa Rosa Kempinski Nairobi', 'area' => 'Westlands', 'rating' => 4.6, 'reviews' => '9,000+ reviews', 'signal' => 'Luxury brand visibility, strong service comments and high review volume.'],
            ['name' => 'Radisson Blu Hotel Nairobi Upper Hill', 'area' => 'Upper Hill', 'rating' => 4.6, 'reviews' => '7,000+ reviews', 'signal' => 'Business-travel visibility, events demand and strong review footprint.'],
            ['name' => 'Sankara Nairobi, Autograph Collection', 'area' => 'Westlands', 'rating' => 4.6, 'reviews' => '6,000+ reviews', 'signal' => 'Premium hospitality positioning and strong guest experience signals.'],
            ['name' => 'Fairmont The Norfolk', 'area' => 'CBD / Harry Thuku Road', 'rating' => 4.5, 'reviews' => '5,000+ reviews', 'signal' => 'Historic hotel brand, tourism visibility and established reputation.'],
            ['name' => 'Sarova Stanley', 'area' => 'CBD', 'rating' => 4.5, 'reviews' => '6,000+ reviews', 'signal' => 'Central location, strong heritage brand and high booking visibility.'],
            ['name' => 'Four Points by Sheraton Nairobi Airport', 'area' => 'JKIA', 'rating' => 4.5, 'reviews' => '6,000+ reviews', 'signal' => 'Airport convenience, business traveller appeal and high review count.'],
            ['name' => 'Movenpick Hotel & Residences Nairobi', 'area' => 'Westlands', 'rating' => 4.5, 'reviews' => '5,000+ reviews', 'signal' => 'Conference, dining and long-stay visibility.'],
            ['name' => 'The Boma Nairobi', 'area' => 'South C', 'rating' => 4.4, 'reviews' => '7,000+ reviews', 'signal' => 'Large review base, event facilities and airport corridor relevance.'],
            ['name' => 'Trademark Hotel', 'area' => 'Gigiri', 'rating' => 4.5, 'reviews' => '4,000+ reviews', 'signal' => 'UN/Gigiri market visibility and modern guest experience.'],
            ['name' => 'Eka Hotel Nairobi', 'area' => 'Mombasa Road', 'rating' => 4.4, 'reviews' => '6,000+ reviews', 'signal' => 'Airport-road location, meetings market and steady review footprint.'],
        ],
    ],
    'best-private-hospitals-nairobi' => [
        'title' => 'Best Private Hospitals in Nairobi by Online Reputation',
        'short_title' => 'Private Hospitals',
        'description' => 'A Nairobi private hospital ranking for market intelligence, supplier targeting and health-sector mapping.',
        'category' => 'Health',
        'location' => 'Nairobi',
        'image' => 'img/services/field-location-verification.png',
        'chart_color' => '#F3525A',
        'cta' => 'Request hospital leads',
        'rows' => [
            ['name' => 'M.P. Shah Hospital', 'area' => 'Parklands', 'rating' => 4.3, 'reviews' => '1,700+ reviews', 'signal' => 'Large review base, specialist services and strong service visibility.'],
            ['name' => 'The Mater Hospital Westlands', 'area' => 'Westlands', 'rating' => 4.1, 'reviews' => '10+ reviews', 'signal' => 'Specialist clinic presence and strong brand recognition.'],
            ['name' => 'Nairobi West Hospital', 'area' => 'Nairobi West', 'rating' => 3.9, 'reviews' => '500+ reviews', 'signal' => 'Large hospital footprint and visible patient feedback.'],
            ['name' => 'Coptic Hospital', 'area' => 'Ngong Road', 'rating' => 3.8, 'reviews' => '1,000+ reviews', 'signal' => 'Known private hospital with wide outpatient visibility.'],
            ['name' => 'The Karen Hospital', 'area' => 'Karen', 'rating' => 3.8, 'reviews' => '700+ reviews', 'signal' => 'Specialist services and strong location-based visibility.'],
            ['name' => 'Gertrude\'s Children\'s Hospital', 'area' => 'Muthaiga', 'rating' => 3.8, 'reviews' => '600+ reviews', 'signal' => 'Recognised paediatric brand and strong family-care visibility.'],
            ['name' => 'Nairobi Women\'s Hospital', 'area' => 'Hurlingham', 'rating' => 3.7, 'reviews' => '900+ reviews', 'signal' => 'Women-focused care brand and large review footprint.'],
            ['name' => 'AAR Hospital', 'area' => 'Kiambu Road', 'rating' => 3.6, 'reviews' => '700+ reviews', 'signal' => 'Insurance-linked brand and visible outpatient demand.'],
            ['name' => 'The Nairobi Hospital', 'area' => 'Upper Hill', 'rating' => 3.3, 'reviews' => '500+ reviews', 'signal' => 'Premium hospital visibility with mixed public sentiment.'],
            ['name' => 'Aga Khan University Hospital Nairobi', 'area' => 'Parklands', 'rating' => 2.7, 'reviews' => '230+ reviews', 'signal' => 'Strong specialist brand, but weaker public review sentiment.'],
        ],
    ],
    'best-restaurants-in-nairobi' => [
        'title' => 'Best Restaurants in Nairobi by Online Reputation',
        'short_title' => 'Restaurants',
        'description' => 'A Nairobi restaurant ranking for hospitality suppliers, delivery platforms, food brands and market researchers.',
        'category' => 'Hospitality',
        'location' => 'Nairobi',
        'image' => 'img/services/field-mystery-shopping.png',
        'chart_color' => '#f6c85f',
        'cta' => 'Request restaurant directory',
        'rows' => [
            ['name' => 'Talisman Restaurant', 'area' => 'Karen', 'rating' => 4.6, 'reviews' => '4,000+ reviews', 'signal' => 'Premium dining visibility and strong guest sentiment.'],
            ['name' => 'Carnivore Restaurant', 'area' => 'Langata Road', 'rating' => 4.5, 'reviews' => '17,000+ reviews', 'signal' => 'High tourist visibility and very large review footprint.'],
            ['name' => 'About Thyme', 'area' => 'Westlands', 'rating' => 4.5, 'reviews' => '3,000+ reviews', 'signal' => 'Strong neighbourhood reputation and repeat dining appeal.'],
            ['name' => 'Nyama Mama Delta', 'area' => 'Westlands', 'rating' => 4.5, 'reviews' => '5,000+ reviews', 'signal' => 'Modern Kenyan dining brand with high social visibility.'],
            ['name' => 'CJ\'s Kilimani', 'area' => 'Kilimani', 'rating' => 4.5, 'reviews' => '10,000+ reviews', 'signal' => 'High volume restaurant brand and strong casual dining demand.'],
            ['name' => 'Fogo Gaucho', 'area' => 'Westlands', 'rating' => 4.5, 'reviews' => '8,000+ reviews', 'signal' => 'Buffet-style dining visibility and large review base.'],
            ['name' => 'Urban Eatery', 'area' => 'Westlands', 'rating' => 4.4, 'reviews' => '4,000+ reviews', 'signal' => 'Business-lunch appeal and multi-cuisine positioning.'],
            ['name' => 'INTI', 'area' => 'Westlands', 'rating' => 4.4, 'reviews' => '3,000+ reviews', 'signal' => 'Premium experience, skyline appeal and strong social mentions.'],
            ['name' => 'Mama Rocks', 'area' => 'Westlands', 'rating' => 4.4, 'reviews' => '3,000+ reviews', 'signal' => 'Youthful brand, burger category visibility and social appeal.'],
            ['name' => 'Java House Kimathi Street', 'area' => 'CBD', 'rating' => 4.3, 'reviews' => '7,000+ reviews', 'signal' => 'Strong brand awareness and high footfall location.'],
        ],
    ],
    'best-schools-in-nairobi' => [
        'title' => 'Best Schools in Nairobi by Online Reputation',
        'short_title' => 'Schools',
        'description' => 'A Nairobi school reputation data pool for education suppliers, parents, training firms and EdTech teams.',
        'category' => 'Education',
        'location' => 'Nairobi',
        'image' => 'img/services/field-enumerators.png',
        'chart_color' => '#00b8d9',
        'cta' => 'Request school directory',
        'rows' => [
            ['name' => 'Brookhouse School', 'area' => 'Karen / Runda', 'rating' => 4.6, 'reviews' => '250+ reviews', 'signal' => 'International curriculum visibility and premium education brand.'],
            ['name' => 'Braeburn School', 'area' => 'Gitanga Road', 'rating' => 4.5, 'reviews' => '180+ reviews', 'signal' => 'Strong international school reputation and established parent awareness.'],
            ['name' => 'Hillcrest International School', 'area' => 'Karen', 'rating' => 4.5, 'reviews' => '150+ reviews', 'signal' => 'Premium school visibility and strong co-curricular reputation.'],
            ['name' => 'Peponi School', 'area' => 'Ruiru / Nairobi market', 'rating' => 4.5, 'reviews' => '100+ reviews', 'signal' => 'Boarding and international curriculum reputation.'],
            ['name' => 'Rusinga School', 'area' => 'Lavington', 'rating' => 4.4, 'reviews' => '170+ reviews', 'signal' => 'Known private school brand and parent review visibility.'],
            ['name' => 'St. Mary\'s School Nairobi', 'area' => 'Lavington', 'rating' => 4.4, 'reviews' => '200+ reviews', 'signal' => 'Longstanding academic reputation and strong alumni visibility.'],
            ['name' => 'Strathmore School', 'area' => 'Lavington', 'rating' => 4.4, 'reviews' => '180+ reviews', 'signal' => 'Academic reputation and strong local brand awareness.'],
            ['name' => 'Light Academy', 'area' => 'Karen', 'rating' => 4.3, 'reviews' => '120+ reviews', 'signal' => 'Private school visibility and positive academic mentions.'],
            ['name' => 'Nairobi Academy', 'area' => 'Karen', 'rating' => 4.3, 'reviews' => '150+ reviews', 'signal' => 'International curriculum visibility and established campus reputation.'],
            ['name' => 'Makini School', 'area' => 'Kilimani / Ngong Road', 'rating' => 4.2, 'reviews' => '250+ reviews', 'signal' => 'Large private school brand and broad parent awareness.'],
        ],
    ],
    'best-saccos-in-kenya' => [
        'title' => 'Best SACCOs in Kenya by Visibility and Reputation',
        'short_title' => 'SACCOs in Kenya',
        'description' => 'A Kenya SACCO ranking data pool for fintechs, lenders, researchers, training firms and B2B teams.',
        'category' => 'Finance',
        'location' => 'Kenya',
        'image' => 'img/services/field-b2b-leads.png',
        'chart_color' => '#0A2540',
        'cta' => 'Request SACCO dataset',
        'rows' => [
            ['name' => 'Stima SACCO', 'area' => 'National', 'rating' => 4.4, 'reviews' => 'High public visibility', 'signal' => 'Large membership, strong brand awareness and digital visibility.'],
            ['name' => 'Mwalimu National SACCO', 'area' => 'National', 'rating' => 4.3, 'reviews' => 'High public visibility', 'signal' => 'Large teacher-membership base and national footprint.'],
            ['name' => 'Kenya Police SACCO', 'area' => 'National', 'rating' => 4.2, 'reviews' => 'High public visibility', 'signal' => 'Strong institutional member base and broad awareness.'],
            ['name' => 'Harambee SACCO', 'area' => 'National', 'rating' => 4.2, 'reviews' => 'High public visibility', 'signal' => 'Longstanding national SACCO brand and member services footprint.'],
            ['name' => 'Safaricom SACCO', 'area' => 'National', 'rating' => 4.2, 'reviews' => 'High public visibility', 'signal' => 'Strong corporate association and digital member visibility.'],
            ['name' => 'Unaitas SACCO', 'area' => 'National', 'rating' => 4.1, 'reviews' => 'High public visibility', 'signal' => 'Broad branch footprint and SME/member lending visibility.'],
            ['name' => 'Imarika SACCO', 'area' => 'Coast / National', 'rating' => 4.1, 'reviews' => 'Moderate-high visibility', 'signal' => 'Regional strength and growing national recognition.'],
            ['name' => 'Tower SACCO', 'area' => 'Central Kenya / National', 'rating' => 4.0, 'reviews' => 'Moderate-high visibility', 'signal' => 'Strong regional SACCO identity and member service visibility.'],
            ['name' => 'Waumini SACCO', 'area' => 'National', 'rating' => 4.0, 'reviews' => 'Moderate-high visibility', 'signal' => 'Faith/community-linked membership and national awareness.'],
            ['name' => 'Mentor SACCO', 'area' => 'Murang\'a / National', 'rating' => 3.9, 'reviews' => 'Moderate visibility', 'signal' => 'Regional depth and business lending relevance.'],
        ],
    ],
    'best-real-estate-companies-nairobi' => [
        'title' => 'Best Real Estate Companies in Nairobi by Online Reputation',
        'short_title' => 'Real Estate Companies',
        'description' => 'A Nairobi real estate company ranking for property buyers, suppliers, consultants and lead generation teams.',
        'category' => 'Real Estate',
        'location' => 'Nairobi',
        'image' => 'img/services/field-location-verification.png',
        'chart_color' => '#F3525A',
        'cta' => 'Request real estate leads',
        'rows' => [
            ['name' => 'HassConsult', 'area' => 'Nairobi', 'rating' => 4.5, 'reviews' => 'Strong visibility', 'signal' => 'Premium property brand, market reports and brokerage visibility.'],
            ['name' => 'Pam Golding Properties Kenya', 'area' => 'Nairobi', 'rating' => 4.5, 'reviews' => 'Strong visibility', 'signal' => 'International brand association and premium property listings.'],
            ['name' => 'Knight Frank Kenya', 'area' => 'Nairobi', 'rating' => 4.4, 'reviews' => 'Strong visibility', 'signal' => 'Commercial property, valuation and agency visibility.'],
            ['name' => 'BuyRentKenya', 'area' => 'Nairobi / Kenya', 'rating' => 4.4, 'reviews' => 'Strong digital visibility', 'signal' => 'High property search visibility and online listing footprint.'],
            ['name' => 'Villa Care Kenya', 'area' => 'Nairobi', 'rating' => 4.3, 'reviews' => 'Strong visibility', 'signal' => 'Property management and sales visibility.'],
            ['name' => 'Lloyd Masika', 'area' => 'Nairobi', 'rating' => 4.2, 'reviews' => 'Strong visibility', 'signal' => 'Longstanding property valuation and agency brand.'],
            ['name' => 'Tysons Limited', 'area' => 'Nairobi', 'rating' => 4.1, 'reviews' => 'Moderate-high visibility', 'signal' => 'Property management and consultancy footprint.'],
            ['name' => 'Username Investment', 'area' => 'Nairobi / satellite towns', 'rating' => 4.1, 'reviews' => 'High public visibility', 'signal' => 'Affordable land sales visibility and buyer awareness.'],
            ['name' => 'Optiven', 'area' => 'Nairobi / Kenya', 'rating' => 4.0, 'reviews' => 'High public visibility', 'signal' => 'Land buying brand visibility and wide market awareness.'],
            ['name' => 'Fanaka Real Estate', 'area' => 'Nairobi / satellite towns', 'rating' => 4.0, 'reviews' => 'Moderate-high visibility', 'signal' => 'Land and plots market visibility.'],
        ],
    ],
    'best-cleaning-companies-nairobi' => [
        'title' => 'Best Cleaning Companies in Nairobi by Online Reputation',
        'short_title' => 'Cleaning Companies',
        'description' => 'A Nairobi cleaning company ranking for facility managers, offices, landlords and procurement teams.',
        'category' => 'Facilities',
        'location' => 'Nairobi',
        'image' => 'img/services/field-mystery-shopping.png',
        'chart_color' => '#00b8d9',
        'cta' => 'Request cleaning company leads',
        'rows' => [
            ['name' => 'Parapet Cleaning Services', 'area' => 'Nairobi', 'rating' => 4.5, 'reviews' => 'Strong visibility', 'signal' => 'Large facilities brand and strong commercial cleaning visibility.'],
            ['name' => 'GM Cleaning Services Kenya', 'area' => 'Nairobi', 'rating' => 4.5, 'reviews' => 'Strong visibility', 'signal' => 'Office, home and post-construction cleaning visibility.'],
            ['name' => 'Isamado Homecare', 'area' => 'Nairobi', 'rating' => 4.4, 'reviews' => 'Moderate-high visibility', 'signal' => 'Residential cleaning, pest control and online service footprint.'],
            ['name' => 'Safisana Home Services', 'area' => 'Nairobi', 'rating' => 4.4, 'reviews' => 'Moderate-high visibility', 'signal' => 'Home and office cleaning service visibility.'],
            ['name' => 'SafiSafi Cleaning Services', 'area' => 'Nairobi', 'rating' => 4.3, 'reviews' => 'Moderate visibility', 'signal' => 'Digital visibility and local cleaning demand.'],
            ['name' => 'Kleen Homes Security Services', 'area' => 'Nairobi', 'rating' => 4.2, 'reviews' => 'Moderate visibility', 'signal' => 'Combined cleaning/security facility service relevance.'],
            ['name' => 'Blue Ring Products', 'area' => 'Nairobi', 'rating' => 4.2, 'reviews' => 'Moderate visibility', 'signal' => 'Cleaning products and service brand visibility.'],
            ['name' => 'Jani-King Kenya', 'area' => 'Nairobi', 'rating' => 4.1, 'reviews' => 'Moderate visibility', 'signal' => 'Commercial cleaning franchise visibility.'],
            ['name' => 'Solcity Cleaning Services', 'area' => 'Nairobi', 'rating' => 4.1, 'reviews' => 'Moderate visibility', 'signal' => 'Residential and office cleaning online presence.'],
            ['name' => 'Topmark Cleaning Services', 'area' => 'Nairobi', 'rating' => 4.0, 'reviews' => 'Moderate visibility', 'signal' => 'Office and home cleaning service visibility.'],
        ],
    ],
    'best-logistics-companies-kenya' => [
        'title' => 'Best Logistics and Import-Export Companies in Kenya by Visibility',
        'short_title' => 'Logistics Companies',
        'description' => 'A Kenya logistics, clearing and forwarding ranking for exporters, importers, SMEs and procurement teams.',
        'category' => 'Logistics',
        'location' => 'Kenya',
        'image' => 'img/blog/import-export-data-kenya-smes.png',
        'chart_color' => '#F3525A',
        'cta' => 'Request logistics leads',
        'rows' => [
            ['name' => 'DHL Express Kenya', 'area' => 'National', 'rating' => 4.5, 'reviews' => 'Very high visibility', 'signal' => 'Global logistics brand and strong courier visibility.'],
            ['name' => 'Siginon Group', 'area' => 'Nairobi / Mombasa', 'rating' => 4.4, 'reviews' => 'High visibility', 'signal' => 'Cargo, logistics and airport/marine services footprint.'],
            ['name' => 'Bollore Transport & Logistics Kenya', 'area' => 'National', 'rating' => 4.3, 'reviews' => 'High visibility', 'signal' => 'Regional logistics brand and freight forwarding relevance.'],
            ['name' => 'Mitchell Cotts Freight Kenya', 'area' => 'Nairobi / Mombasa', 'rating' => 4.3, 'reviews' => 'High visibility', 'signal' => 'Clearing, forwarding and warehousing visibility.'],
            ['name' => 'Kuehne+Nagel Kenya', 'area' => 'National', 'rating' => 4.2, 'reviews' => 'High visibility', 'signal' => 'Global freight brand and business logistics relevance.'],
            ['name' => 'Maersk Kenya', 'area' => 'Mombasa / Nairobi', 'rating' => 4.2, 'reviews' => 'High visibility', 'signal' => 'Shipping, ocean freight and import/export relevance.'],
            ['name' => 'Kenfreight East Africa', 'area' => 'Mombasa / Nairobi', 'rating' => 4.1, 'reviews' => 'High visibility', 'signal' => 'Clearing, forwarding and regional cargo footprint.'],
            ['name' => 'Sendy', 'area' => 'Nairobi / Kenya', 'rating' => 4.0, 'reviews' => 'High digital visibility', 'signal' => 'Tech-enabled delivery and SME logistics awareness.'],
            ['name' => 'Riley Services / Freight Forwarders Kenya', 'area' => 'Nairobi', 'rating' => 4.0, 'reviews' => 'Moderate visibility', 'signal' => 'Freight forwarding and business logistics presence.'],
            ['name' => 'Africa Logistics Properties', 'area' => 'Nairobi', 'rating' => 3.9, 'reviews' => 'Moderate-high visibility', 'signal' => 'Warehousing and industrial logistics ecosystem relevance.'],
        ],
    ],
    'best-digital-marketing-agencies-kenya' => [
        'title' => 'Best Digital Marketing Agencies in Kenya by Online Reputation',
        'short_title' => 'Digital Agencies',
        'description' => 'A Kenya digital agency ranking for SMEs, brands, NGOs and procurement teams comparing online marketing partners.',
        'category' => 'Marketing',
        'location' => 'Kenya',
        'image' => 'img/services/field-brand-ambassadors.png',
        'chart_color' => '#00b8d9',
        'cta' => 'Request agency shortlist',
        'rows' => [
            ['name' => 'Dentsu Kenya', 'area' => 'Nairobi', 'rating' => 4.5, 'reviews' => 'High brand visibility', 'signal' => 'Regional agency network and large-brand campaign visibility.'],
            ['name' => 'Scanad Kenya', 'area' => 'Nairobi', 'rating' => 4.4, 'reviews' => 'High brand visibility', 'signal' => 'Longstanding creative and media agency reputation.'],
            ['name' => 'Ogilvy Africa', 'area' => 'Nairobi', 'rating' => 4.4, 'reviews' => 'High brand visibility', 'signal' => 'Global network, creative visibility and campaign footprint.'],
            ['name' => 'Squad Digital', 'area' => 'Nairobi', 'rating' => 4.3, 'reviews' => 'High digital visibility', 'signal' => 'Digital-first agency positioning and brand campaign visibility.'],
            ['name' => 'Growthpad Digital Consulting', 'area' => 'Nairobi', 'rating' => 4.3, 'reviews' => 'Moderate-high visibility', 'signal' => 'SME and performance marketing visibility.'],
            ['name' => 'Agency Africa Interactive', 'area' => 'Nairobi', 'rating' => 4.2, 'reviews' => 'Moderate-high visibility', 'signal' => 'Web, digital and campaign execution visibility.'],
            ['name' => 'Wild Fusion Kenya', 'area' => 'Nairobi', 'rating' => 4.2, 'reviews' => 'Moderate-high visibility', 'signal' => 'Digital marketing and regional agency visibility.'],
            ['name' => 'Akus Digital Solution', 'area' => 'Nairobi', 'rating' => 4.1, 'reviews' => 'Moderate visibility', 'signal' => 'SME digital marketing and web visibility.'],
            ['name' => 'Pettinsky', 'area' => 'Nairobi', 'rating' => 4.1, 'reviews' => 'Moderate visibility', 'signal' => 'Digital marketing, branding and online presence visibility.'],
            ['name' => 'OraDMA', 'area' => 'Nairobi', 'rating' => 4.0, 'reviews' => 'Moderate visibility', 'signal' => 'Performance marketing and online training visibility.'],
        ],
    ],
    'best-maternity-hospitals-nairobi' => [
        'title' => 'Best Maternity Hospitals in Nairobi by Online Reputation',
        'short_title' => 'Maternity Hospitals',
        'description' => 'A Nairobi maternity hospital ranking data pool for healthcare market intelligence and facility shortlisting.',
        'category' => 'Health',
        'location' => 'Nairobi',
        'image' => 'img/services/field-location-verification.png',
        'chart_color' => '#F3525A',
        'cta' => 'Request maternity dataset',
        'rows' => [
            ['name' => 'M.P. Shah Hospital', 'area' => 'Parklands', 'rating' => 4.3, 'reviews' => '1,700+ reviews', 'signal' => 'Large review base, specialist services and maternity visibility.'],
            ['name' => 'Marie Stopes Eastleigh Maternity & Nursing Home', 'area' => 'Eastleigh', 'rating' => 4.2, 'reviews' => '80+ reviews', 'signal' => 'Maternity-specific facility with strong positive care comments.'],
            ['name' => 'Jacaranda Maternity Wallet Centre', 'area' => 'Umoja/Kayole', 'rating' => 3.9, 'reviews' => '130+ reviews', 'signal' => 'Dedicated maternity brand, visible packages and multi-branch presence.'],
            ['name' => 'Pumwani Maternity Hospital', 'area' => 'Pumwani', 'rating' => 3.8, 'reviews' => '130+ reviews', 'signal' => 'High maternity visibility and large public hospital footprint.'],
            ['name' => 'Patanisho Maternity and Nursing Home', 'area' => 'Kayole', 'rating' => 4.0, 'reviews' => '20+ reviews', 'signal' => 'Maternity-focused service comments and local care visibility.'],
            ['name' => 'Kasarani Maternity & Nursing Home', 'area' => 'Kasarani', 'rating' => 3.7, 'reviews' => '60+ reviews', 'signal' => 'Maternity-specific facility with visible delivery experience feedback.'],
            ['name' => 'Nairobi West Hospital', 'area' => 'Nairobi West', 'rating' => 3.9, 'reviews' => '500+ reviews', 'signal' => 'Large general hospital footprint with maternity service visibility.'],
            ['name' => 'The Mater Hospital Westlands', 'area' => 'Westlands', 'rating' => 4.1, 'reviews' => '10+ reviews', 'signal' => 'Ante-natal and obstetrics/gynaecology clinic visibility.'],
            ['name' => 'The Nairobi Hospital', 'area' => 'Upper Hill', 'rating' => 3.3, 'reviews' => '500+ reviews', 'signal' => 'Premium hospital visibility with mixed public feedback.'],
            ['name' => 'Aga Khan University Hospital Nairobi', 'area' => 'Parklands', 'rating' => 2.7, 'reviews' => '230+ reviews', 'signal' => 'Strong specialist brand, but weaker overall public review sentiment.'],
        ],
    ],
];

function rrda_get_ranking_pages() {
    global $rrdaRankingPages;
    return $rrdaRankingPages;
}

function rrda_get_ranking_page($slug) {
    global $rrdaRankingPages;
    return $rrdaRankingPages[$slug] ?? null;
}
